[options]
; Config mínima para demo local. NO usar tal cual en producción.
admin_passwd = admin_master_password_change_me
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = ^odoo_demo$
list_db = True
proxy_mode = False
